name: Documentation Quality

on:
  push:
    branches: [main, develop]
    paths: ['docs/**', 'README.md']
  pull_request:
    branches: [main]
    paths: ['docs/**', 'README.md']

jobs:
  docs-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint docs/**/*.md README.md
          
      - name: Run docs quality check
        run: node scripts/docs-quality.js
        
      - name: Validate mermaid diagrams
        run: |
          npm install -g @mermaid-js/mermaid-cli
          find docs -name "*.md" -exec grep -l "```mermaid" {} \; | \
          while read file; do
            echo "Validating diagrams in $file"
            # Extract and validate mermaid blocks
          done
          
      - name: Check for broken links
        run: |
          npm install -g markdown-link-check
          find docs -name "*.md" -exec markdown-link-check {} \;
          markdown-link-check README.md