name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run unit tests with coverage
      run: yarn test --coverage --watchAll=false
      
    - name: Generate coverage badges
      run: node scripts/generate-badges.js
      
    - name: SonarQube Scan
      uses: sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        
  e2e-tests:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Setup iOS Simulator
      run: |
        xcrun simctl create "iPhone 14" "iPhone 14"
        xcrun simctl boot "iPhone 14"
        
    - name: Build iOS app for Detox
      run: yarn detox build --configuration ios.sim.debug
      
    - name: Run Detox E2E tests
      run: yarn detox test --configuration ios.sim.debug
      
  accessibility-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run accessibility tests
      run: yarn test --testPathPattern=a11y --coverage=false
      
    - name: Check accessibility compliance
      run: |
        if ! yarn test --testPathPattern=a11y --passWithNoTests; then
          echo "❌ Accessibility tests failed"
          exit 1
        else
          echo "✅ Accessibility tests passed"
        fi